### ISSUE TITLE
Settlement building

### ISSUE THREAD

**Issue by hthoma20** [alexweininger/android-catan#243]
On my turn, I roll, immediately select the intersection on which I want to build the settlement (it is a valid location and I have the resources). I get the message "select only one intersection".
I have selected only one intersection.
A work around to the bug is to select another intersection and then deselect it.

**Comment by alexweininger** [comment]
@dborg291 when a user builds anything or rolls the dice the selections need to be cleared

**Comment by alexweininger** [comment]
This was being caused by the selected intersections / hexes not being properly reset after building, ending your turn, etc.

This has been fixed by a few things:
- selected intersections reset when building anything.
- resets when turn it over.
- player is no longer able to select intersections / hexes if it is not their turn.
- at the beginning of your turn the selected intersections are cleared just to be safe.
