### ISSUE TITLE
Storing Data

### ISSUE THREAD

**Issue by Lexden12** [alexweininger/android-catan#4]
I really find your data structures storing the hexes and intersections quite interesting.
I am thinking that it might be possible to optimize it to further minimize the amount of memory used, but it seems like a smart solution to a tough problem.
I am not sure if having both a list and a graph is necessary, but it will be interesting to see how it works out.

**Comment by alexweininger** [comment]
Yeah one of the memory quirks is that for the adjacency matrix for relating hexagons to hexagons, and intersections to intersections is that the matrix is reflected diagonally (symmetric matrix). Since we are storing it in a 2d array which can be queried like: arr[2][7] returns if hex 2 is adjacent to hex 7. And arr[7][2] is the exact same, essentially wasting half of the array.

**Comment by alexweininger** [comment]
Thanks for your feedback Alex!
